[package]
name = "cargo-clawless"
description = "Generate and develop CLIs with Clawless"

version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

categories = ["command-line-utilities"]
keywords = ["cli", "framework"]

[[bin]]
name = "cargo-clawless"
path = "src/main.rs"

[dependencies]
anyhow = { workspace = true }
bon = { workspace = true }
clawless = { workspace = true }
convert_case = { workspace = true }
getset = { workspace = true }
indoc = { workspace = true }
typed-fields = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
tokio = { workspace = true }
trycmd = { workspace = true }

[lints]
workspace = true
