VERSION 0.8

LINT:
    FUNCTION

    FROM ghcr.io/zizmorcore/zizmor:1.14.1
    WORKDIR /clawless

    # Copy the source code into the container
    COPY --dir .github .

    # Run static analysis on the GitHub Actions workflows
    RUN zizmor ./
