[workspace]
members = ["crates/*", "examples/*"]
exclude = ["crates/cargo-clawless/tests/commands/new.out"]

# Opt-in to the new feature resolver introduced in Rust 1.85 and Edition 2024.
# https://doc.rust-lang.org/cargo/reference/resolver.html#resolver-versions
resolver = "3"

[workspace.package]
version = "0.6.1"
edition = "2024"

license = "Apache-2.0 OR MIT"
repository = "https://github.com/aonyx-ai/clawless.git"

# darling 0.23 requires Rust 1.88.0 or greater
rust-version = "1.88.0"

[workspace.dependencies]
anyhow = "1.0.16"
assert_cmd = "2.1.1"
async-trait = "0.1"
bon = "3"
clap = { version = "4.3.0", features = ["cargo", "derive"] }
clawless = { path = "crates/clawless", version = "=0.6.1" }
clawless-cli = { path = "crates/clawless-cli", version = "=0.6.1" }
clawless-core = { path = "crates/clawless-core", version = "=0.6.1" }
clawless-derive = { path = "crates/clawless-derive", version = "=0.6.1" }
clawless-tui = { path = "crates/clawless-tui", version = "=0.6.1" }
convert_case = ">=0.1,<1"
libc = "0.2"
darling = ">=0.23,<1"
erased-serde = ">=0.3,<1"
getset = ">=0.1,<1"
indoc = "2.0.0"
inventory = "0.3.0"
kawauso-process = ">=0.1,<1"
predicates = "3"
proc-macro2 = "1.0.86"
quote = "1.0.28"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
syn = { version = "3.0.0", features = ["extra-traits", "full"] }
tempfile = "3"
thiserror = "2"
tokio = { version = "1", features = [
  "macros",
  "rt-multi-thread",
  "signal",
  "sync",
] }
tokio-util = ">=0.4,<1"
trybuild = "1.0.86"
trycmd = ">=0.9, <2"
typed-fields = ">=0.6,<1"

[workspace.lints.clippy]
# Require documentation on private items as well, since that helps with long-term maintainability.
missing_docs_in_private_items = "warn"

# Require errors, panics, and unsafe code to be documented.
missing_errors_doc = "warn"
missing_panics_doc = "warn"
missing_safety_doc = "warn"
unnecessary_safety_doc = "warn"

# `unwrap` and `expect` can cause panics, which is why we ban them from production code. Tests are
# exempt, which `.clippy.toml` configures.
expect_used = "warn"
unwrap_used = "warn"

# Forbid printing anything to stdout or stderr.
print_stderr = "warn"
print_stdout = "warn"

# Prefer `mod.rs` over `name.rs` so that every module is a self-contained unit.
self_named_module_files = "warn"

[workspace.lints.rust]
# Detect explicit lifetime requirements that the compiler can infer.
explicit_outlives_requirements = "deny"

# Types must implement or derive `Debug` so that they can be easily debugged.
missing_debug_implementations = "deny"

# Require documentation for all public items
missing_docs = "deny"

# Public but unreachable items are likely a mistake.
unreachable_pub = "deny"

# Unsafe code can lead to undefined behavior and security vulnerabilities.
unsafe_code = "deny"
