[package]
name = "clawless-core"
description = "Types and traits for building command-line applications"

version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

categories = ["command-line-interface"]
keywords = ["cli", "framework"]

[dependencies]
bon = { workspace = true }
erased-serde = { workspace = true }
getset = { workspace = true }
kawauso-process = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true }
typed-fields = { workspace = true }

[dev-dependencies]
serde_json = { workspace = true }
tempfile = { workspace = true }
tokio = { workspace = true, features = ["time"] }

[lints]
workspace = true
