//! TUI application runner
//!
//! This module defines [`ApplicationRunner`], which encapsulates the full lifecycle of a TUI
//! application: event channel creation, context construction, projection setup, signal handling, and
//! application execution. The `main!()` macro dispatches to `ApplicationRunner::run` when the
//! resolved leaf is an application.
//!
//! Application authors do not interact with this module directly. The `main!()` macro calls
//! [`ApplicationRunner::run`] with the resolved matches and exec function pointer.

use std::future::Future;

use clawless_core::cancellation::Cancellation;
use clawless_core::context::Context;
use clawless_core::event::event_channel;
use clawless_core::output::Output;
use clawless_core::signal::wait_for_shutdown;

use crate::projection::Projection;

/// TUI application runner
///
/// Encapsulates the lifecycle of running a TUI application: creating the event channel,
/// constructing the [`Context`], building a [`Projection`] inside a Tokio runtime, registering
/// signal handlers, and calling the application function. Unlike `CommandRunner`, there is no
/// presenter — the application owns its own render loop and queries the projection for accumulated
/// state.
///
/// # Examples
///
/// ```rust,ignore
/// // This is what main!() expands to for applications:
/// ResolvedLeaf::Application { matches, exec } => {
///     clawless::tui::runner::ApplicationRunner::run(matches, exec)
/// }
/// ```
///
/// [`Context`]: clawless_core::context::Context
/// [`Projection`]: crate::projection::Projection
// r[impl dispatch.exec.application-runner]
pub struct ApplicationRunner;

impl ApplicationRunner {
    /// Runs a TUI application to completion
    ///
    /// Sets up the application lifecycle:
    ///
    /// 1. Creates a [`Cancellation`] token for cooperative shutdown
    /// 2. Creates an event channel and builds the [`Context`]
    /// 3. Creates a Tokio runtime
    /// 4. Inside the runtime, creates a [`Projection`] (which spawns a background drain task)
    /// 5. Spawns the signal handler and calls the application function
    ///
    /// The [`Projection`] must be created inside the Tokio runtime because its constructor calls
    /// `tokio::spawn` to start the background event drain.
    ///
    /// # Arguments
    ///
    /// * `matches` — The parsed [`ArgMatches`] for this application leaf, as resolved by the
    ///   subcommand tree walk.
    /// * `exec` — Executes the application with the given matches, context, and projection.
    ///   Generated by the `#[application]` macro.
    ///
    /// # Errors
    ///
    /// Returns an error if context construction fails (e.g., the current working directory cannot be
    /// determined), if the Tokio runtime cannot be created, or if the application itself fails.
    ///
    /// [`ArgMatches`]: clap::ArgMatches
    /// [`Cancellation`]: clawless_core::cancellation::Cancellation
    /// [`Context`]: clawless_core::context::Context
    /// [`Projection`]: crate::projection::Projection
    pub fn run<F>(
        matches: clap::ArgMatches,
        exec: fn(clap::ArgMatches, Context, Projection) -> F,
    ) -> Result<(), Box<dyn std::error::Error>>
    where
        F: Future<Output = anyhow::Result<()>> + Send + 'static,
    {
        let cancellation = Cancellation::new();
        let (sender, receiver) = event_channel();
        let output = Output::new(sender);

        let context = Context::builder()
            .cancellation(cancellation.clone())
            .output(output)
            .build()?;

        let rt = tokio::runtime::Runtime::new()?;
        rt.block_on(async {
            let projection = Projection::new(receiver);

            tokio::spawn(wait_for_shutdown(cancellation));
            exec(matches, context, projection).await
        })?;

        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn trait_send() {
        fn assert_send<T: Send>() {}
        assert_send::<ApplicationRunner>();
    }

    #[test]
    fn trait_sync() {
        fn assert_sync<T: Sync>() {}
        assert_sync::<ApplicationRunner>();
    }

    #[test]
    fn trait_unpin() {
        fn assert_unpin<T: Unpin>() {}
        assert_unpin::<ApplicationRunner>();
    }
}
