//! CLI command runner
//!
//! This module defines [`CommandRunner`], which encapsulates the full lifecycle of a CLI command:
//! argument parsing, event channel creation, context construction, signal handling, and terminal
//! presentation. The `main!()` macro delegates to `CommandRunner::run` so that the orchestration
//! logic lives in testable library code rather than in macro-generated output.
//!
//! Application authors do not interact with this module directly. The `main!()` macro calls
//! [`CommandRunner::run`] with the generated `init` and `exec` functions.

use std::future::Future;

use clawless_core::cancellation::Cancellation;
use clawless_core::context::Context;
use clawless_core::event::event_channel;
use clawless_core::output::Output;
use clawless_core::signal::wait_for_shutdown;

use crate::error::CommandResult;
use crate::output::OutputFlags;
use crate::presenter::{Presenter, TerminalPresenter};

/// CLI command runner
///
/// Encapsulates the lifecycle of running a CLI command: parsing arguments, creating the event
/// channel, constructing the [`Context`], registering signal handlers, and presenting output
/// through a [`TerminalPresenter`]. The `main!()` macro generates a thin wrapper that delegates to
/// [`CommandRunner::run`].
///
/// # Examples
///
/// ```rust,ignore
/// // This is what main!() expands to:
/// fn main() -> Result<(), Box<dyn std::error::Error>> {
///     clawless::runner::CommandRunner::run(
///         commands::clawless_init,
///         commands::clawless_exec,
///     )
/// }
/// ```
pub struct CommandRunner;

impl CommandRunner {
    /// Runs a CLI command to completion
    ///
    /// Sets up the full command lifecycle:
    ///
    /// 1. Creates a [`Cancellation`] token for cooperative shutdown
    /// 2. Augments the command with output flags (`--quiet`, `--verbose`, `--json`) and parses CLI
    ///    arguments
    /// 3. Creates an event channel and builds the [`Context`]
    /// 4. Configures a [`TerminalPresenter`] with the parsed output flags
    /// 5. Creates a Tokio runtime, spawns the signal handler, and runs the command through the
    ///    presenter
    ///
    /// # Arguments
    ///
    /// * `init` — Returns the root [`clap::Command`] with all registered subcommands. Generated by
    ///   the `commands!()` macro as `clawless_init`.
    /// * `exec` — Dispatches to the matched subcommand given parsed arguments and context. Generated
    ///   by the `commands!()` macro as `clawless_exec`.
    ///
    /// # Errors
    ///
    /// Returns an error if context construction fails (e.g., the current working directory cannot be
    /// determined), if the Tokio runtime cannot be created, or if the command itself fails.
    ///
    /// [`Cancellation`]: clawless_core::cancellation::Cancellation
    /// [`Context`]: clawless_core::context::Context
    /// [`TerminalPresenter`]: crate::presenter::TerminalPresenter
    pub fn run<E, F>(init: fn() -> clap::Command, exec: E) -> Result<(), Box<dyn std::error::Error>>
    where
        E: FnOnce(clap::ArgMatches, Context) -> F,
        F: Future<Output = CommandResult> + Send + 'static,
    {
        let cancellation = Cancellation::new();

        let app = OutputFlags::augment_command(init());
        let matches = app.get_matches();
        let output_flags = OutputFlags::from_arg_matches(&matches);

        let (sender, receiver) = event_channel();
        let output = Output::new(sender);

        let context = Context::builder()
            .cancellation(cancellation.clone())
            .output(output)
            .build()?;

        let presenter = TerminalPresenter::builder()
            .receiver(receiver)
            .verbosity(output_flags.verbosity())
            .mode(output_flags.mode())
            .build();

        let rt = tokio::runtime::Runtime::new()?;
        rt.block_on(async {
            tokio::spawn(wait_for_shutdown(cancellation));

            presenter.present(Box::pin(exec(matches, context))).await
        })?;

        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn trait_send() {
        fn assert_send<T: Send>() {}
        assert_send::<CommandRunner>();
    }

    #[test]
    fn trait_sync() {
        fn assert_sync<T: Sync>() {}
        assert_sync::<CommandRunner>();
    }

    #[test]
    fn trait_unpin() {
        fn assert_unpin<T: Unpin>() {}
        assert_unpin::<CommandRunner>();
    }
}
