[package]
name = "output"
description = "Demonstrates Output, verbosity, and output mode in clawless"

version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

# We do not want to publish examples to crates.io, since they provide no value
# or functionality on their own.
publish = false

[dependencies]
clawless = { workspace = true }
serde = { workspace = true }

[dev-dependencies]
trycmd = { workspace = true }

[lints]
workspace = true
