[package]
name = "clawless-tui"
description = "Presentation layer for TUI-based applications using the Clawless framework"

version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

categories = ["command-line-interface"]
keywords = ["cli", "framework", "tui"]

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true }
clawless-core = { workspace = true }
tokio = { workspace = true }

[dev-dependencies]
serde = { workspace = true }
