[package]
name = "clawless"
description = "An opinionated framework for building command-line applications"

version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

categories = ["command-line-interface"]
keywords = ["cli", "framework"]

[dependencies]
anyhow = { workspace = true }
bon = { workspace = true }
clap = { workspace = true }
clawless-derive = { workspace = true }
erased-serde = { workspace = true }
getset = { workspace = true }
inventory = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true }
typed-fields = { workspace = true }

[dev-dependencies]
trybuild = { workspace = true }
