[package]
name = "clawless"
description = "An opinionated framework for building command-line applications"

version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

categories = ["command-line-interface"]
keywords = ["cli", "framework"]

[dependencies]
clap = { workspace = true }
clawless-cli = { workspace = true }
clawless-core = { workspace = true }
clawless-derive = { workspace = true }
clawless-tui = { workspace = true }
inventory = { workspace = true }
serde = { workspace = true }
tokio = { workspace = true }

[dev-dependencies]
trybuild = { workspace = true }
